name: Update submodule pointer on chalk-private

on:
  push:
    branches: [main]

jobs:
  dispatch:
    permissions:
      contents: 'read'

    runs-on: ubuntu-latest
    steps:
      - name: Repository dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.CHALK_DOCS_PAT }}
          repository: chalk-ai/chalk-private
          event-type: docs-update
          client-payload: '{"ref": "${{ github.ref_name }}", "sha": "${{ github.sha }}"}'